// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// randomize
LogicalMatrix randomize(NumericMatrix occ_matrix, unsigned int S);
RcppExport SEXP _netcutter_randomize(SEXP occ_matrixSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type occ_matrix(occ_matrixSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(randomize(occ_matrix, S));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netcutter_randomize", (DL_FUNC) &_netcutter_randomize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_netcutter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
