# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randomize_bitfiddling <- function(occ_matrix, S) {
    .Call(`_netcutter_randomize_bitfiddling`, occ_matrix, S)
}

randomize_bitfiddling3 <- function(occ_matrix, S) {
    .Call(`_netcutter_randomize_bitfiddling3`, occ_matrix, S)
}

randomize_bitfiddling2 <- function(occ_matrix, S) {
    .Call(`_netcutter_randomize_bitfiddling2`, occ_matrix, S)
}

randomize2 <- function(occ_matrix, S) {
    .Call(`_netcutter_randomize2`, occ_matrix, S)
}

randomize <- function(occ_matrix, S) {
    .Call(`_netcutter_randomize`, occ_matrix, S)
}

